@startuml pert2

actor Mahasiswa as mahasiswa
actor Dosen as dosen 

package Kampus {
    usecase "Pilih Mata Kuliah" as U1
    usecase "Ruang Perkuliahan" as U2
    usecase "Menerima Penjadwalan Perkuliahan" as U3
    usecase "Jadwal Kuliah" as U4
    usecase "Mengajar" as U5  
}

mahasiswa --> U3
mahasiswa--> U1
dosen --> U5
U1 .> U2
U1 .> U4

@enduml